compatibility_flags = ["nodejs_compat"]
compatibility_date = "2024-09-23"

[build]
  command = "npm run build"
  cwd = "projects/PDF-Guru-v2"
  watch_dir = "projects/PDF-Guru-v2"

[[pages]]
  bucket = ".vercel/output/static"
